version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: trello_db
    environment:
      POSTGRES_DB: trello_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trello_network

networks:
  trello_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local